apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db1
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db1
  template:
    metadata:
      labels:
        app: mysql-db1
    spec:
      containers:
      - image: mysql
        name: mysql-database
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root1234"

